import 'package:flutter/material.dart';

import 'asset_metadata.dart';

/// Fiat currency metadata: code, name, optional flag/emoji.
class FiatCurrencyMetadata extends AssetMetadata {
  @override
  final String id;

  final String name;

  final String? flagEmoji;

  const FiatCurrencyMetadata({
    required this.id,
    required this.name,
    this.flagEmoji,
  });

  @override
  String get displayLabel => id;

  @override
  String? get displaySubtitle => name;

  @override
  Widget? get leadingWidget => flagEmoji != null
      ? Text(flagEmoji!, style: const TextStyle(fontSize: 24))
      : null;

  static const List<FiatCurrencyMetadata> supported = [
    FiatCurrencyMetadata(id: 'AED', name: 'UAE Dirham'),
    FiatCurrencyMetadata(id: 'AFN', name: 'Afghan Afghani'),
    FiatCurrencyMetadata(id: 'ALL', name: 'Albanian Lek'),
    FiatCurrencyMetadata(id: 'AMD', name: 'Armenian Dram'),
    FiatCurrencyMetadata(id: 'ANG', name: 'Netherlands Antillean Guilder'),
    FiatCurrencyMetadata(id: 'AOA', name: 'Angolan Kwanza'),
    FiatCurrencyMetadata(id: 'ARS', name: 'Argentine Peso'),
    FiatCurrencyMetadata(id: 'AUD', name: 'Australian Dollar'),
    FiatCurrencyMetadata(id: 'AWG', name: 'Aruban Florin'),
    FiatCurrencyMetadata(id: 'AZN', name: 'Azerbaijani Manat'),
    FiatCurrencyMetadata(id: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark'),
    FiatCurrencyMetadata(id: 'BBD', name: 'Barbadian Dollar'),
    FiatCurrencyMetadata(id: 'BDT', name: 'Bangladeshi Taka'),
    FiatCurrencyMetadata(id: 'BGN', name: 'Bulgarian Lev'),
    FiatCurrencyMetadata(id: 'BHD', name: 'Bahraini Dinar'),
    FiatCurrencyMetadata(id: 'BIF', name: 'Burundian Franc'),
    FiatCurrencyMetadata(id: 'BMD', name: 'Bermudan Dollar'),
    FiatCurrencyMetadata(id: 'BND', name: 'Brunei Dollar'),
    FiatCurrencyMetadata(id: 'BOB', name: 'Bolivian Boliviano'),
    FiatCurrencyMetadata(id: 'BRL', name: 'Brazilian Real'),
    FiatCurrencyMetadata(id: 'BSD', name: 'Bahamian Dollar'),
    FiatCurrencyMetadata(id: 'BTN', name: 'Bhutanese Ngultrum'),
    FiatCurrencyMetadata(id: 'BWP', name: 'Botswanan Pula'),
    FiatCurrencyMetadata(id: 'BYN', name: 'Belarusian Ruble'),
    FiatCurrencyMetadata(id: 'BZD', name: 'Belize Dollar'),
    FiatCurrencyMetadata(id: 'CAD', name: 'Canadian Dollar'),
    FiatCurrencyMetadata(id: 'CDF', name: 'Congolese Franc'),
    FiatCurrencyMetadata(id: 'CHF', name: 'Swiss Franc'),
    FiatCurrencyMetadata(id: 'CLP', name: 'Chilean Peso'),
    FiatCurrencyMetadata(id: 'CNY', name: 'Chinese Yuan'),
    FiatCurrencyMetadata(id: 'COP', name: 'Colombian Peso'),
    FiatCurrencyMetadata(id: 'CRC', name: 'Costa Rican Colón'),
    FiatCurrencyMetadata(id: 'CUP', name: 'Cuban Peso'),
    FiatCurrencyMetadata(id: 'CVE', name: 'Cape Verdean Escudo'),
    FiatCurrencyMetadata(id: 'CZK', name: 'Czech Koruna'),
    FiatCurrencyMetadata(id: 'DJF', name: 'Djiboutian Franc'),
    FiatCurrencyMetadata(id: 'DKK', name: 'Danish Krone'),
    FiatCurrencyMetadata(id: 'DOP', name: 'Dominican Peso'),
    FiatCurrencyMetadata(id: 'DZD', name: 'Algerian Dinar'),
    FiatCurrencyMetadata(id: 'EGP', name: 'Egyptian Pound'),
    FiatCurrencyMetadata(id: 'ERN', name: 'Eritrean Nakfa'),
    FiatCurrencyMetadata(id: 'ETB', name: 'Ethiopian Birr'),
    FiatCurrencyMetadata(id: 'EUR', name: 'Euro'),
    FiatCurrencyMetadata(id: 'FJD', name: 'Fijian Dollar'),
    FiatCurrencyMetadata(id: 'FKP', name: 'Falkland Islands Pound'),
    FiatCurrencyMetadata(id: 'GBP', name: 'British Pound'),
    FiatCurrencyMetadata(id: 'GEL', name: 'Georgian Lari'),
    FiatCurrencyMetadata(id: 'GHS', name: 'Ghanaian Cedi'),
    FiatCurrencyMetadata(id: 'GIP', name: 'Gibraltar Pound'),
    FiatCurrencyMetadata(id: 'GMD', name: 'Gambian Dalasi'),
    FiatCurrencyMetadata(id: 'GNF', name: 'Guinean Franc'),
    FiatCurrencyMetadata(id: 'GTQ', name: 'Guatemalan Quetzal'),
    FiatCurrencyMetadata(id: 'GYD', name: 'Guyanaese Dollar'),
    FiatCurrencyMetadata(id: 'HKD', name: 'Hong Kong Dollar'),
    FiatCurrencyMetadata(id: 'HNL', name: 'Honduran Lempira'),
    FiatCurrencyMetadata(id: 'HRK', name: 'Croatian Kuna'),
    FiatCurrencyMetadata(id: 'HTG', name: 'Haitian Gourde'),
    FiatCurrencyMetadata(id: 'HUF', name: 'Hungarian Forint'),
    FiatCurrencyMetadata(id: 'IDR', name: 'Indonesian Rupiah'),
    FiatCurrencyMetadata(id: 'ILS', name: 'Israeli New Shekel'),
    FiatCurrencyMetadata(id: 'INR', name: 'Indian Rupee'),
    FiatCurrencyMetadata(id: 'IQD', name: 'Iraqi Dinar'),
    FiatCurrencyMetadata(id: 'IRR', name: 'Iranian Rial'),
    FiatCurrencyMetadata(id: 'ISK', name: 'Icelandic Króna'),
    FiatCurrencyMetadata(id: 'JMD', name: 'Jamaican Dollar'),
    FiatCurrencyMetadata(id: 'JOD', name: 'Jordanian Dinar'),
    FiatCurrencyMetadata(id: 'JPY', name: 'Japanese Yen'),
    FiatCurrencyMetadata(id: 'KES', name: 'Kenyan Shilling'),
    FiatCurrencyMetadata(id: 'KGS', name: 'Kyrgystani Som'),
    FiatCurrencyMetadata(id: 'KHR', name: 'Cambodian Riel'),
    FiatCurrencyMetadata(id: 'KMF', name: 'Comorian Franc'),
    FiatCurrencyMetadata(id: 'KRW', name: 'South Korean Won'),
    FiatCurrencyMetadata(id: 'KWD', name: 'Kuwaiti Dinar'),
    FiatCurrencyMetadata(id: 'KYD', name: 'Cayman Islands Dollar'),
    FiatCurrencyMetadata(id: 'KZT', name: 'Kazakhstani Tenge'),
    FiatCurrencyMetadata(id: 'LAK', name: 'Laotian Kip'),
    FiatCurrencyMetadata(id: 'LBP', name: 'Lebanese Pound'),
    FiatCurrencyMetadata(id: 'LKR', name: 'Sri Lankan Rupee'),
    FiatCurrencyMetadata(id: 'LRD', name: 'Liberian Dollar'),
    FiatCurrencyMetadata(id: 'LSL', name: 'Lesotho Loti'),
    FiatCurrencyMetadata(id: 'LYD', name: 'Libyan Dinar'),
    FiatCurrencyMetadata(id: 'MAD', name: 'Moroccan Dirham'),
    FiatCurrencyMetadata(id: 'MDL', name: 'Moldovan Leu'),
    FiatCurrencyMetadata(id: 'MGA', name: 'Malagasy Ariary'),
    FiatCurrencyMetadata(id: 'MKD', name: 'Macedonian Denar'),
    FiatCurrencyMetadata(id: 'MMK', name: 'Myanma Kyat'),
    FiatCurrencyMetadata(id: 'MNT', name: 'Mongolian Tugrik'),
    FiatCurrencyMetadata(id: 'MOP', name: 'Macanese Pataca'),
    FiatCurrencyMetadata(id: 'MRU', name: 'Mauritanian Ouguiya'),
    FiatCurrencyMetadata(id: 'MUR', name: 'Mauritian Rupee'),
    FiatCurrencyMetadata(id: 'MVR', name: 'Maldivian Rufiyaa'),
    FiatCurrencyMetadata(id: 'MWK', name: 'Malawian Kwacha'),
    FiatCurrencyMetadata(id: 'MXN', name: 'Mexican Peso'),
    FiatCurrencyMetadata(id: 'MYR', name: 'Malaysian Ringgit'),
    FiatCurrencyMetadata(id: 'MZN', name: 'Mozambican Metical'),
    FiatCurrencyMetadata(id: 'NAD', name: 'Namibian Dollar'),
    FiatCurrencyMetadata(id: 'NGN', name: 'Nigerian Naira'),
    FiatCurrencyMetadata(id: 'NIO', name: 'Nicaraguan Córdoba'),
    FiatCurrencyMetadata(id: 'NOK', name: 'Norwegian Krone'),
    FiatCurrencyMetadata(id: 'NPR', name: 'Nepalese Rupee'),
    FiatCurrencyMetadata(id: 'NZD', name: 'New Zealand Dollar'),
    FiatCurrencyMetadata(id: 'OMR', name: 'Omani Rial'),
    FiatCurrencyMetadata(id: 'PAB', name: 'Panamanian Balboa'),
    FiatCurrencyMetadata(id: 'PEN', name: 'Peruvian Sol'),
    FiatCurrencyMetadata(id: 'PGK', name: 'Papua New Guinean Kina'),
    FiatCurrencyMetadata(id: 'PHP', name: 'Philippine Peso'),
    FiatCurrencyMetadata(id: 'PKR', name: 'Pakistani Rupee'),
    FiatCurrencyMetadata(id: 'PLN', name: 'Polish Zloty'),
    FiatCurrencyMetadata(id: 'PYG', name: 'Paraguayan Guarani'),
    FiatCurrencyMetadata(id: 'QAR', name: 'Qatari Rial'),
    FiatCurrencyMetadata(id: 'RON', name: 'Romanian Leu'),
    FiatCurrencyMetadata(id: 'RSD', name: 'Serbian Dinar'),
    FiatCurrencyMetadata(id: 'RUB', name: 'Russian Ruble'),
    FiatCurrencyMetadata(id: 'RWF', name: 'Rwandan Franc'),
    FiatCurrencyMetadata(id: 'SAR', name: 'Saudi Riyal'),
    FiatCurrencyMetadata(id: 'SBD', name: 'Solomon Islands Dollar'),
    FiatCurrencyMetadata(id: 'SCR', name: 'Seychellois Rupee'),
    FiatCurrencyMetadata(id: 'SDG', name: 'Sudanese Pound'),
    FiatCurrencyMetadata(id: 'SEK', name: 'Swedish Krona'),
    FiatCurrencyMetadata(id: 'SGD', name: 'Singapore Dollar'),
    FiatCurrencyMetadata(id: 'SHP', name: 'Saint Helena Pound'),
    FiatCurrencyMetadata(id: 'SLL', name: 'Sierra Leonean Leone'),
    FiatCurrencyMetadata(id: 'SOS', name: 'Somali Shilling'),
    FiatCurrencyMetadata(id: 'SRD', name: 'Surinamese Dollar'),
    FiatCurrencyMetadata(id: 'SSP', name: 'South Sudanese Pound'),
    FiatCurrencyMetadata(id: 'STN', name: 'São Tomé and Príncipe Dobra'),
    FiatCurrencyMetadata(id: 'SYP', name: 'Syrian Pound'),
    FiatCurrencyMetadata(id: 'SZL', name: 'Swazi Lilangeni'),
    FiatCurrencyMetadata(id: 'THB', name: 'Thai Baht'),
    FiatCurrencyMetadata(id: 'TJS', name: 'Tajikistani Somoni'),
    FiatCurrencyMetadata(id: 'TMT', name: 'Turkmenistani Manat'),
    FiatCurrencyMetadata(id: 'TND', name: 'Tunisian Dinar'),
    FiatCurrencyMetadata(id: 'TOP', name: "Tongan Paʻanga"),
    FiatCurrencyMetadata(id: 'TRY', name: 'Turkish Lira'),
    FiatCurrencyMetadata(id: 'TTD', name: 'Trinidad and Tobago Dollar'),
    FiatCurrencyMetadata(id: 'TWD', name: 'New Taiwan Dollar'),
    FiatCurrencyMetadata(id: 'TZS', name: 'Tanzanian Shilling'),
    FiatCurrencyMetadata(id: 'UAH', name: 'Ukrainian Hryvnia'),
    FiatCurrencyMetadata(id: 'UGX', name: 'Ugandan Shilling'),
    FiatCurrencyMetadata(id: 'USD', name: 'US Dollar'),
    FiatCurrencyMetadata(id: 'UYU', name: 'Uruguayan Peso'),
    FiatCurrencyMetadata(id: 'UZS', name: 'Uzbekistan Som'),
    FiatCurrencyMetadata(id: 'VES', name: 'Venezuelan Bolívar'),
    FiatCurrencyMetadata(id: 'VND', name: 'Vietnamese Dong'),
    FiatCurrencyMetadata(id: 'VUV', name: 'Vanuatu Vatu'),
    FiatCurrencyMetadata(id: 'WST', name: 'Samoan Tala'),
    FiatCurrencyMetadata(id: 'XAF', name: 'Central African CFA Franc'),
    FiatCurrencyMetadata(id: 'XCD', name: 'East Caribbean Dollar'),
    FiatCurrencyMetadata(id: 'XOF', name: 'West African CFA Franc'),
    FiatCurrencyMetadata(id: 'XPF', name: 'CFP Franc'),
    FiatCurrencyMetadata(id: 'YER', name: 'Yemeni Rial'),
    FiatCurrencyMetadata(id: 'ZAR', name: 'South African Rand'),
    FiatCurrencyMetadata(id: 'ZMW', name: 'Zambian Kwacha'),
    FiatCurrencyMetadata(id: 'ZWL', name: 'Zimbabwean Dollar'),
  ];
}
